site_name: VA Data Commons Documentation
site_url: https://va.data-commons.org/
repo_url: https://github.com/uc-cdis/vadc-mkdocs
nav:
  - Return to VADC: https://va.data-commons.org/
  - Home: index.md
  - Getting Started: getting-started.md
  - Data access and analysis: 
    - data-analysis/index.md
    - Data Dictionary App: data-analysis/data-dictionary.md
    - OHDSI ATLAS App: data-analysis/OHDSI-atlas.md
    - GWAS App: data-analysis/gwas.md
    - GWAS Results App: data-analysis/gwas-results.md
  - FAQ: faq.md

theme:
  favicon: img/va-favicon.ico
  logo: img/va-logo.png
  name: material
  
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: vadc_platform
      toggle:
        icon: material/eye
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: vadc_platform_dark
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tracking

# Additional CSS
extra_css:
  - /stylesheets/extra.css

use_directory_urls: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: True
      baselevel: 1
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - search
  - mkdocs-video:
      is_video: True